DROP TABLE IF EXISTS file_attachment;

DROP TABLE IF EXISTS request;

DROP TABLE IF EXISTS response;

DROP TABLE IF EXISTS endpoint;

DROP TABLE IF EXISTS "user";

DROP TYPE IF EXISTS http_method;

DROP TYPE IF EXISTS plan;